---
- hosts: 192.168.10.41

  tasks:

   - name: Install required packages for compiling and transcoding video nginx
     become: yes
     apt:
      name: "{{ item }}"
      update_cache: true 
      state: present 
     with_items: 
      - 'build-essential'
      - 'libpcre3' 
      - 'libpcre3-dev'
      - 'libssl-dev'
      - 'zlib1g-dev'     
      - 'ffmpeg'

   - name: Install unzip for unzipping rtmp module
     become: yes
     apt:
      name: unzip
      state: present


   - name: download and extract latest nginx source code

     unarchive:
      src: https://nginx.org/download/nginx-1.15.3.tar.gz
      dest: /home/anigma
      remote_src: yes

   - name: download and extract RTMP module for nginx

     unarchive:
      src: https://github.com/arut/nginx-rtmp-module/archive/master.zip
      dest: /home/anigma
      remote_src: yes

   - name: Configuring NGINX source with RTMP modules
   
     command: ./configure --prefix=/usr/share/nginx \
            --sbin-path=/usr/sbin/nginx \
            --modules-path=/usr/lib/nginx/modules \
            --conf-path=/etc/nginx/nginx.conf \
            --error-log-path=/var/log/nginx/error.log \
            --http-log-path=/var/log/nginx/access.log \
            --pid-path=/run/nginx.pid \
            --lock-path=/var/lock/nginx.lock \
            --user=www-data \
            --group=www-data \
            --build=Ubuntu \ 
            --with-http_ssl_module \
            --add-module=../nginx-rtmp-module-master \
            --with-file-aio
     args:
      chdir: /home/anigma/nginx-1.15.3

   - name: Installing NGINX
   
     become: yes
     shell: make && make install
     args:
      chdir: /home/anigma/nginx-1.15.3

   - name: Create required HLS directory
   
     become: yes
     file:
      path: /HLS/live
      state: directory
      owner: root
      mode: 0755

   - name: Copy nginx RTMP and HLS configuration file
   
     become: yes
     copy:
      src: /home/anigma/ansible/nginx.conf
      dest: /etc/nginx/nginx.conf
      owner: root
      group: root
      mode: 0644

